# navbar
menu:
  Home: /
  Archives: /archives/

# site icon
favicon: /favicon.ico

# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  anchor: "ยง"

# comments
comments:
  post: true
  about: true

# article contents sidebar
sidebar: true

# Analytics
## Baidu Analytics
baidu_analytics:
## Google Analytics
google_analytics: UA-87967706-1

# Comments
## Duoshuo
duoshuo_shortname:
## Disqus
disqus_shortname: sahil-cc.disqus.com

# Social links
social:
  email: sahilahuja@gmail.com
  stack-overflow:
  twitter:
  facebook:
  github: 
  weibo: 
  zhihu: 
  rss: /atom.xml